[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = "doccloud/**,docs/**,*.md,backend/**,.env.*.example,DEPLOYMENT-CONFIG.md"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
