# Railway Deployment Configuration
# https://docs.railway.app/deploy/config-as-code

[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 300

[service]
# Service name in Railway
name = "quokka-backend"

# Volume for persistent SQLite database
[[service.volumes]]
mountPath = "/app/backend"
name = "quokka-db"
